apiVersion: v1
kind: Namespace
metadata:
  name: backend-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: node:18-alpine
          ports:
            - containerPort: 3000
          command: ["node"]
          args:
            - "-e"
            - |
              const http = require('http');
              http.createServer((req, res) => {
                res.writeHead(200, {'Content-Type': 'application/json'});
                res.end(JSON.stringify({ message: 'Hello from backend (backend-team)' }));
              }).listen(3000);
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  namespace: backend-team
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3000
