apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-manual-config
data:
  default.conf: |
    server {
        listen 80;

        location /frontend/ {
            proxy_pass http://frontend-service:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://node-backend-service.backend-team.svc.cluster.local:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-nginx
  template:
    metadata:
      labels:
        app: manual-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-manual-config
---
apiVersion: v1
kind: Service
metadata:
  name: manual-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: manual-nginx
  ports:
    - port: 80
      targetPort: 80
